---
title: "R_muticlass_dalex"
author: "m.oka"
date: "6/22/2020"
output: html_document
---


# 1. datasetの準備


## iris datasetの確認


```{r}
head(iris)
```


## データセットの次元を確認


```{r}
dim(iris)
```


## データセットの要約統計量


```{r}
summary(iris)
```


## データ型の確認


```{r}
sapply(iris, class)
```


# 2. ランダムフォレストでモデリング


## 訓練データとテストデータに分割


```{r}
library("randomForest")
```


## 訓練データとテストデータに分割


```{r}
set.seed(1313)
iris.rows = nrow(iris) # 150
train.rate = 0.7 # 訓練データの比率
train.index <- sample(iris.rows, iris.rows * train.rate)
iris.train = iris[train.index,] # 訓練データ
iris.test = iris[-train.index,] # テストデータ
cat("train=", nrow(iris.train), " test=", nrow(iris.test))
```


## 訓練データの確認


```{r}
head(iris.train)
```

```{r}
dim(iris.train)
```


## テストデータの確認


```{r}
head(iris.test)
```

```{r}
dim(iris.test)
```


## 学習


```{r}
rf_model <- randomForest(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data=iris.train)
rf_model
```


## 予測


```{r}
rf_pred <- predict(rf_model, iris.test)
```


## 予測結果の確認


```{r}
table(rf_pred, iris.test$Species) # 予測結果の検証
sum(rf_pred == iris.test$Species) / length(rf_pred) # 正解率
```



# 3. DALEX（instance level）


## libraryインポート


```{r}
library('DALEX')
```


## instance dataを作成


```{r}
# 予測がsetosaになるはずのデータを作ってみる
iris_setosa <- data.frame(Sepal.Length=4.7, Sepal.Width=3.2, Petal.Length=1.3, Petal.Width=0.2)
```


## 作成したinstance dataで予測


```{r}
rf_pred_setosa <- predict(rf_model, iris_setosa)
rf_pred_setosa
```


## explain objectを作成


```{r}
# explainでpredict
exp_rf <- explain(rf_model, data = iris.train, y=iris.train$Species)
pred_exp <- predict(exp_rf, iris.test)
```


## 予測結果


```{r}
pred_exp
```


## SHAPをplot


```{r}
# B（順番の生成数）はとりあえず25に
shap <- variable_attribution(exp_rf, iris_setosa, type = 'shap', B=25)
plot(shap)
```


# 4. DALEX（data set levelで使ってみる）


## variable importanceを計算


```{r}
vip <- model_parts(exp_rf, loss_function = loss_cross_entropy, type = 'variable_importance')
vip
```


## variable importanceをplot


```{r}
library('ggplot2')
plot(vip) + ggtitle('variable importance')
```

