- [dataset](https://www.kaggle.com/uciml/pima-indians-diabetes-database)

```{r results = 'hide'}
library(dplyr) # dataframe操作パッケージ
library(ForImp) # 欠損値の補完パッケージ
library(caret) # train_test_split/dummyVarsを行うパッケージ
library(tidyr) # 欠損値削除
library(rms)
library(randomForest)
library(ggplot2)
```

```{r results = 'hide'}
df <- read.csv('diabetes.csv', header=TRUE)
```

```{r}
head(df)
```


```{r}
df[(df$Glucose==0 & df$Outcome==0), "Glucose"] <- NaN
df[(df$Glucose==0 & df$Outcome==1), "Glucose"] <- NaN
df <- df %>% drop_na(Glucose)
df[df$BloodPressure==0 & df$Outcome==0, "BloodPressure"] <- NaN
df[df$BloodPressure==0 & df$Outcome==1, "BloodPressure"] <- NaN
df <- df %>% drop_na(BloodPressure)
df <- df[, !(colnames(df) %in% c("SkinThickness", "Insulin"))]
df[df$BMI==0 & df$Outcome==0, "BMI"] <- NaN
df[df$BMI==0 & df$Outcome==1, "BMI"] <- NaN
df <- df %>% drop_na(BMI)
```

```{r}
set.seed(2020)
# 分割したレコード（今回は80%）の行番号を受け取る
# データの分布を維持したまま分割
train_index <- createDataPartition(df$Outcome, p=0.8, list=FALSE)
```

```{r results = 'hide'}
train <- df[train_index, ]
test <- df[-train_index, ]
```

```{r}
head(train)
```


```{r results = 'hide'}
numerical_features = c('Pregnancies', 'Glucose', 'BloodPressure', 'BMI', 'DiabetesPedigreeFunction', 'Age')
categolical_features = c(NULL)
```


```{r results = 'hide'}
# 中央値で補完
# train[, numerical_features] <-  medianimp(train[, numerical_features]) %>% data.frame()
# test[, numerical_features] <- medianimp(test[, numerical_features]) %>% data.frame()
# 標準化
# train[, numerical_features] <- scale(train[, numerical_features]) %>% data.frame()
# test[, numerical_features] <- scale(test[, numerical_features]) %>% data.frame()
```

```{r results = 'hide'}
## missingで補完
# X_train[is.na(X_train[, categolical_features])] <- 'missing'
# X_train[is.na(X_train[, categolical_features])] <- 'missing'
# X_test[is.null(X_test[, categolical_features])] <- 'missing'
# X_test[is.null(X_test[, categolical_features])] <- 'missing'
## One-Hot Encoding
# dummy_model <- dummyVars(~categolical_features, data=X_train, fullRank=FALSE)
# dummy_vars <- predict(dummy_model, X_train)
# X_train <- data.frame(X_train, dummy_vars)
```


```{r}
dim(train)
```

```{r}
sum(train$Outcome==1)
```


```{r}
set.seed(2020)
# ロジスティック回帰
clf_lr <- lrm(Outcome == 1 ~ Pregnancies + Glucose + BloodPressure + BMI + DiabetesPedigreeFunction + Age, train)
# ランダムフォレスト
clf_rf <- randomForest(Outcome ~ Pregnancies + Glucose + BloodPressure + BMI + DiabetesPedigreeFunction + Age, data = train)
```


```{r}
exp_clf_lr <- DALEX::explain(model = clf_lr, data = test, y = test$Outcome==1, label='Logistic Regression')
exp_clf_rf <- DALEX::explain(model = clf_rf, data = test, y = test$Outcome==1, label='Random Forest')
```


```{r}
kei <- data.frame(
         Pregnancies = 6,
         Glucose = 148,
         BloodPressure = 72,
         BMI = 33.6,
         DiabetesPedigreeFunction = 0.627, 
         Age = 50)

keiko <- data.frame(
         Pregnancies = 1,
         Glucose = 85,
         BloodPressure = 66,
         BMI = 26.6,
         DiabetesPedigreeFunction = 0.351, 
         Age = 31)
```

```{r}
pred_clf_lr_kei <- predict(clf_lr, kei, type = 'fitted')
pred_clf_rf_kei <- predict(clf_rf, kei)
pred_clf_lr_keiko <- predict(clf_lr, keiko, type = 'fitted')
pred_clf_rf_keiko <- predict(clf_rf, keiko)
```


BD Plot

```{r}
bd_clf_lr_kei <- DALEX::predict_parts(explainer = exp_clf_lr, new_observation = kei, type = "break_down")
bd_clf_rf_kei <- DALEX::predict_parts(explainer = exp_clf_rf, new_observation = kei, type = "break_down")
bd_clf_lr_keiko <- DALEX::predict_parts(explainer = exp_clf_lr, new_observation = keiko, type = "break_down")
bd_clf_rf_keiko <- DALEX::predict_parts(explainer = exp_clf_rf, new_observation = keiko, type = "break_down")
plot(bd_clf_lr_kei)
plot(bd_clf_rf_kei)
plot(bd_clf_lr_keiko)
plot(bd_clf_rf_keiko)
```


```{r}
shap_clf_lr_kei <- DALEX::predict_parts(explainer = exp_clf_lr, new_observation = kei, type = "shap", B = 10)
shap_clf_rf_kei <- DALEX::predict_parts(explainer = exp_clf_rf, new_observation = kei, type = "shap", B = 10)
shap_clf_lr_keiko <- DALEX::predict_parts(explainer = exp_clf_lr, new_observation = keiko, type = "shap", B = 10)
shap_clf_rf_keiko <- DALEX::predict_parts(explainer = exp_clf_rf, new_observation = keiko, type = "shap", B = 10)
plot(shap_clf_lr_kei)
plot(shap_clf_rf_kei)
plot(shap_clf_lr_keiko)
plot(shap_clf_rf_keiko)
```

```{r}
cp_clf_lr_2 <- DALEX::individual_profile(explainer = exp_clf_lr, new_observation = rbind(kei, keiko))
library(ingredients)
plot(cp_clf_lr_2, color = "_ids_", variables = c("Glucose", "Pregnancies")) + 
  scale_color_manual(name = "names:", breaks = 1:2, 
            values = c("#4378bf", "#8bdcbe"), 
            labels = c("kei" , "keiko")) + 
  ggtitle("Ceteris-paribus profile - Logistic Regression", "")

cp_clf_rf_2 <- DALEX::individual_profile(explainer = exp_clf_rf, new_observation = rbind(kei, keiko))
library(ingredients)
plot(cp_clf_rf_2, color = "_ids_", variables = c("Glucose", "Pregnancies")) + 
  scale_color_manual(name = "names:", breaks = 1:2, 
            values = c("#4378bf", "#8bdcbe"), 
            labels = c("kei" , "keiko")) + 
  ggtitle("Ceteris-paribus profile - Random Forest", "")
```


```{r}
mp_clf_lr <- DALEX::model_performance(explainer = exp_clf_lr)
mp_clf_rf <- DALEX::model_performance(explainer = exp_clf_rf)

plot(mp_clf_lr, mp_clf_rf, geom = "prc")
plot(mp_clf_lr, mp_clf_rf, geom = "roc")
plot(mp_clf_lr, mp_clf_rf, geom = "ecdf")
```

```{r}
set.seed(2020)
mpa_clf_lr <- DALEX::model_parts(explainer = exp_clf_lr)
mpa_clf_rf <- DALEX::model_parts(explainer = exp_clf_rf)

plot(mpa_clf_lr)
plot(mpa_clf_rf)
```

